// Cell-Plane OpenAPI 3.1 — source of truth for API Reference.dc.html. Exported as a JS module so the reference page can import it without CORS/fetch.
export default {
  "openapi": "3.1.0",
  "info": { "title": "Cell-Plane Control Plane API", "version": "1.0.0-draft", "description": "Multi-tenant control plane for agentic work. Every call carries org, project, principal and task scope in the token. All errors are RFC 9457 problem details. All externally triggered actions accept an Idempotency-Key." },
  "servers": [{ "url": "https://cellplane.example/v1" }],
  "security": [{ "bearer": [] }],
  "x-scope-tiers": ["org", "ws", "principal", "task"],
  "x-conventions": {
    "idempotency": "Send Idempotency-Key on every POST/PUT/DELETE. Same key + same body → the original result with 200. Same key + different body → 409 idempotency-conflict.",
    "pagination": "Cursor: ?limit= (≤ 200) and ?cursor=. Responses carry next_cursor when more exist.",
    "ratelimit": "IETF RateLimit-Limit / RateLimit-Remaining / RateLimit-Reset headers on every response. 429 carries Retry-After.",
    "versioning": "/v1 in the path. Additive changes need no bump. Deprecations announced via Sunset and Deprecation headers (RFC 8594).",
    "timestamps": "RFC 3339 UTC.",
    "money": "Decimal string in USD, e.g. \"3.40\"."
  },
  "components": {
    "securitySchemes": { "bearer": { "type": "http", "scheme": "bearer", "bearerFormat": "JWT", "description": "OIDC access token carrying org_id, project_ids, roles. Systems obtain one via POST /auth/exchange (RFC 8693)." } },
    "schemas": {
      "Problem": { "type": "object", "description": "Every error body.", "properties": { "type": { "type": "string", "description": "Stable URN, resolvable at /problem-types/{name}.", "example": "urn:cellplane:problem:verb-not-applicable" }, "title": { "type": "string", "example": "Verb not applicable" }, "status": { "type": "integer", "example": 409 }, "detail": { "type": "string", "example": "approve is only valid for parked tasks; t-0217 is stuck" }, "instance": { "type": "string", "example": "/v1/tasks/t-0217/commands/cmd_3a" } } },
      "TaskSpec": { "type": "object", "description": "Declared intent, acceptance criteria and steps for a unit of work. Immutable per revision.", "properties": { "id": { "type": "string", "example": "spec_8f1" }, "rev": { "type": "integer", "description": "Revision, starts at 1.", "example": 1 }, "parent_rev": { "type": "integer", "description": "Revision this one was derived from.", "example": null }, "intent": { "type": "string", "description": "One unit of work, stated so a task can do it alone.", "example": "Summarise one vendor's public security docs into the posture template, citing every claim" }, "acceptance_criteria": { "type": "array", "items": { "type": "string" }, "description": "Acceptance criteria. Each clause is a Evaluator criterion.", "example": ["every claim carries a source URL", "template fields populated", "≤ 600 words"] }, "steps": { "type": "array", "items": { "$ref": "#/components/schemas/Step" }, "description": "Plan steps with stage and class." }, "template": { "type": "string", "description": "Template this Task specification was created from, if any.", "example": "research" }, "class": { "type": "string", "enum": ["f-", "i-", "b-", "cli-"], "description": "Default model class.", "example": "b-" }, "author": { "type": "string", "example": "opr_maria" }, "created_at": { "type": "string", "format": "date-time" } } },
      "Step": { "type": "object", "description": "One planned unit inside a Task specification, with a stage and class.", "properties": { "name": { "type": "string", "example": "Extract claims" }, "stage": { "type": "string", "enum": ["Intake", "Build", "Verify", "Gate", "Done"], "example": "Build" }, "class": { "type": "string", "example": "b-" }, "gate": { "type": "boolean", "description": "True when a human approval is required before this step.", "example": false }, "sandbox_class": { "type": "string", "enum": ["standard", "hardened", "long"], "description": "Sandbox class this step requires.", "example": "hardened" } } },
      "Plan": { "type": "object", "description": "Planner output: units, steps, cost.", "properties": { "units": { "type": "integer", "description": "Tasks this Task specification will dispatch.", "example": 15 }, "steps": { "type": "array", "items": { "$ref": "#/components/schemas/Step" } }, "cost": { "$ref": "#/components/schemas/CostEstimate" } } },
      "CostEstimate": { "type": "object", "description": "estimate · per_task · ceiling, in USD decimal strings.", "properties": { "estimate": { "type": "string", "description": "Expected spend across all units.", "example": "3.30" }, "per_task": { "type": "string", "example": "0.22" }, "ceiling": { "type": "string", "description": "Hard cap across all units. Exceeding it stops the unit.", "example": "9.00" }, "currency": { "type": "string", "example": "USD" } } },
      "Workflow": { "type": "object", "description": "A Task specification revision bound to a trigger and a class; the thing that dispatches tasks.", "properties": { "id": { "type": "string", "example": "wf_9c" }, "task_spec": { "type": "string", "example": "spec_8f1" }, "rev": { "type": "integer", "example": 1 }, "intake": { "type": "string", "enum": ["http", "git", "schedule", "a2a", "cli"], "example": "http" }, "rrule": { "type": "string", "description": "RFC 5545 recurrence when intake is schedule.", "example": "FREQ=HOURLY" }, "paused": { "type": "boolean", "description": "Dispatch paused. Running tasks finish their step.", "example": false }, "webhook": { "type": "string", "description": "Intake URL for push intakes.", "example": "https://cellplane.example/v1/intake/wf_9c" }, "secret_ref": { "type": "string", "description": "Handle of the webhook signing secret. Never the value.", "example": "urn:secret:org_7f/intake/wf_9c" }, "tasks": { "type": "integer", "example": 15 } } },
      "Task": { "type": "object", "description": "One unit of work assigned to one sandbox under one Task specification revision. Status, budget, problem and commands attach here.", "properties": { "id": { "type": "string", "example": "t-0217" }, "session": { "type": "string", "description": "ACP session id of the conversation with the harness in the sandbox.", "example": "sess_4b2" }, "workflow": { "type": "string", "example": "wf_9c" }, "spec_rev": { "type": "integer", "example": 1 }, "status": { "type": "string", "enum": ["submitted", "working", "input-required", "auth-required", "completed", "canceled", "rejected", "failed"], "description": "A2A TaskState.", "example": "working" }, "substate": { "type": "string", "enum": ["waiting", "stalled", "blocked"], "description": "Cell-Plane extension while status is working. blocked = a problem is open (UI: Stuck).", "example": "blocked" }, "step_idx": { "type": "integer", "example": 2 }, "stage": { "type": "string", "example": "Build" }, "model": { "type": "string", "description": "Model group the task is using.", "example": "claude-code-cli" }, "budget": { "type": "object", "properties": { "spent": { "type": "string", "example": "3.10" }, "ceiling": { "type": "string", "example": "6.00" } } }, "sandbox": { "$ref": "#/components/schemas/Sandbox" }, "dep": { "type": "string", "description": "Task this one waits on, if any.", "example": null }, "problem": { "$ref": "#/components/schemas/TaskProblem" }, "exhausted": { "type": "boolean", "description": "Every ladder rung fired to its limit.", "example": false }, "updated_at": { "type": "string", "format": "date-time" } } },
      "Sandbox": { "type": "object", "description": "The isolated execution instance one agent runs in. Technology-neutral; one square on the fleet map.", "properties": { "id": { "type": "string", "example": "sbx-1217" }, "class": { "type": "string", "enum": ["standard", "hardened", "long"], "description": "Requested by the Task specification; callers never name a technology.", "example": "hardened" }, "isolation": { "type": "string", "enum": ["process", "user-space-kernel", "microvm", "vm", "wasm"], "description": "How this sandbox is isolated.", "example": "microvm" }, "runtime": { "type": "string", "description": "OCI runtime that created it.", "example": "firecracker-containerd" }, "egress": { "type": "boolean", "description": "Network egress enabled. Default false.", "example": false } } },
      "TaskProblem": { "type": "object", "description": "Why the task needs attention. RFC 9457 shape plus suggested action.", "properties": { "type": { "type": "string", "example": "urn:cellplane:problem:evaluation-failed" }, "title": { "type": "string", "example": "Evaluation FAIL ×2" }, "detail": { "type": "string", "example": "Identical diff resubmitted after FAIL — agent is looping" }, "failed_clause": { "type": "string", "example": "no new @ts-ignore or any" }, "suggested_action": { "type": "string", "example": "redefine" }, "opened_at": { "type": "string", "format": "date-time" } } },
      "Command": { "type": "object", "description": "A user or ladder intent applied to one or more tasks; recorded in the Ledger.", "properties": { "id": { "type": "string", "example": "cmd_3a" }, "verb": { "type": "string", "enum": ["nudge", "redefine", "escalate", "extend", "restart", "rollback", "split", "reassign", "skip", "cancel", "approve", "grant", "answer", "return", "reject"], "example": "extend" }, "tasks": { "type": "array", "items": { "type": "string" }, "example": ["t-0217"] }, "args": { "type": "object", "description": "Verb-specific. extend: {pct}. redefine: {acceptance_criteria[], intent?}. reassign: {model}. answer|return: {text}. rollback: {to_rev}. split: {parts}.", "example": { "pct": 50 } }, "actor": { "type": "string", "description": "Principal, or playbook:<type>/<verb>.", "example": "opr_maria" }, "act": { "type": "array", "items": { "type": "string" }, "description": "Delegation chain when actor is an agent.", "example": [] }, "policy": { "type": "object", "properties": { "decision": { "type": "string", "enum": ["allow", "deny", "pending"] }, "engine": { "type": "string", "example": "opa" }, "bundle": { "type": "string", "example": "org_7f/prj_a1@v12" } } }, "effects": { "type": "array", "items": { "type": "string" }, "example": ["budget.ceiling:9.00", "dispatch.resume"] }, "compensable_until": { "type": "string", "format": "date-time" }, "compensated_by": { "type": "string", "example": null } } },
      "Playbook": { "type": "object", "description": "Ordered recovery ladder for a problem type; each rung fires a bounded number of times per task.", "properties": { "problem_type": { "type": "string", "example": "urn:cellplane:problem:tool-timeout" }, "rungs": { "type": "array", "items": { "type": "object", "properties": { "verb": { "type": "string", "example": "restart" }, "max": { "type": "integer", "description": "Fires per task before the next rung.", "example": 1 } } } }, "human_verb": { "type": "string", "description": "Suggested to the user once rungs are exhausted.", "example": "reassign" }, "enabled": { "type": "object", "description": "Per-workflow on/off. Missing = on.", "additionalProperties": { "type": "boolean" }, "example": { "wf_9c": true } }, "stats": { "type": "object", "properties": { "tried": { "type": "integer", "example": 42 }, "resolved_pct": { "type": "integer", "example": 71 }, "automatic_pct": { "type": "integer", "example": 64 } } } } },
      "Recommendation": { "type": "object", "description": "A recurring problem type in a workflow with a proposed change to the Task specification or dispatch config.", "properties": { "id": { "type": "string", "example": "rec_1" }, "problem_type": { "type": "string", "example": "urn:cellplane:problem:tool-timeout" }, "workflow": { "type": "string", "example": "wf_9c" }, "count": { "type": "integer", "example": 4 }, "cost_lost": { "type": "string", "example": "1.84" }, "proposal": { "type": "object", "properties": { "target": { "type": "string", "enum": ["document.acceptance_criteria", "document.steps", "document.intent", "dispatch.config", "schedule"], "example": "dispatch.config" }, "text": { "type": "string", "example": "Raise per-tool ceiling to 120s for this workflow" } } }, "state": { "type": "string", "enum": ["proposed", "applied", "dismissed"], "example": "proposed" }, "applied_rev": { "type": "integer", "example": null }, "before": { "type": "integer", "description": "Recurrences before apply." }, "after": { "type": "integer", "description": "Recurrences since apply." } } },
      "Org": { "type": "object", "description": "Hard tenancy boundary: own identity provider, keys, secrets namespace, storage, routers, policy bundle, Ledger partition.", "properties": { "id": { "type": "string", "example": "org_7f" }, "name": { "type": "string", "example": "Acme" }, "region": { "type": "string", "example": "eu-west-1" }, "retention_days": { "type": "integer", "example": 365 }, "status": { "type": "string", "enum": ["provisioning", "active", "read_only", "deleting"], "example": "active" }, "bindings": { "type": "object", "description": "Verification state per binding.", "properties": { "identity": { "$ref": "#/components/schemas/BindingState" }, "keys": { "$ref": "#/components/schemas/BindingState" }, "storage": { "$ref": "#/components/schemas/BindingState" }, "routers": { "$ref": "#/components/schemas/BindingState" }, "policy": { "$ref": "#/components/schemas/BindingState" } } } } },
      "BindingState": { "type": "object", "properties": { "status": { "type": "string", "enum": ["unset", "verifying", "verified", "failed"], "example": "verified" }, "verification": { "type": "string", "description": "Run id of the last conformance run.", "example": "run_8812" }, "problem": { "$ref": "#/components/schemas/Problem" } } },
      "IdentityBinding": { "type": "object", "properties": { "issuer": { "type": "string", "example": "https://id.acme.example" }, "audience": { "type": "string", "example": "cellplane" }, "role_claim": { "type": "string", "description": "Claim path that carries roles.", "example": "cellplane.roles" }, "spiffe_trust_domain": { "type": "string", "example": "acme.example" } } },
      "StorageBinding": { "type": "object", "properties": { "endpoint": { "type": "string", "example": "https://s3.eu-west-1.amazonaws.com" }, "bucket": { "type": "string", "example": "acme-cellplane" }, "prefix": { "type": "string", "example": "prod/" }, "credential_ref": { "type": "string", "description": "Secret reference for a role scoped to the prefix.", "example": "urn:secret:org_7f/s3" }, "sse": { "type": "string", "enum": ["none", "s3", "kms"], "example": "kms" } } },
      "RouterBinding": { "type": "object", "properties": { "class": { "type": "string", "enum": ["f-", "i-", "b-", "cli-"], "example": "i-" }, "endpoint": { "type": "string", "description": "OpenAI-compatible base URL.", "example": "https://llm.acme.example/v1" }, "key_ref": { "type": "string", "description": "Secret reference for a virtual key with a hard budget cap.", "example": "urn:secret:org_7f/litellm/i" }, "ceiling_per_task": { "type": "string", "example": "4.00" }, "models": { "type": "array", "items": { "type": "string" }, "example": ["i-default", "i-claude-sonnet", "i-escalate"] } } },
      "PolicyBinding": { "type": "object", "properties": { "engine": { "type": "string", "enum": ["opa", "cedar", "custom"], "example": "opa" }, "bundle_url": { "type": "string", "example": "https://policy.acme.example/bundles/cellplane.tar.gz" }, "decision_url": { "type": "string", "description": "Required when engine is custom.", "example": null } } },
      "Project": { "type": "object", "description": "Soft tenancy unit inside an organisation: owns Task specifications, Workflows, Playbooks, budget, memberships.", "properties": { "id": { "type": "string", "example": "prj_a1" }, "org": { "type": "string", "example": "org_7f" }, "name": { "type": "string", "example": "vendor-review" }, "default_class": { "type": "string", "example": "i-" }, "budget": { "$ref": "#/components/schemas/Budget" }, "alert_prefs": { "type": "object", "example": { "stuck": true, "parked": true, "ceiling": true, "stalled": false } } } },
      "Budget": { "type": "object", "description": "Ceiling, per-task default, spent and alert threshold for a scope.", "properties": { "ceiling": { "type": "string", "example": "40.00" }, "per_task": { "type": "string", "example": "0.60" }, "spent": { "type": "string", "example": "12.40" }, "alert_at": { "type": "number", "description": "Fraction of ceiling that raises an alert.", "example": 0.8 } } },
      "Membership": { "type": "object", "description": "viewer · operator · approver · admin. Per project.", "properties": { "sub": { "type": "string", "example": "opr_li" }, "role": { "type": "string", "enum": ["viewer", "operator", "approver", "admin"], "example": "operator" }, "granted_by": { "type": "string", "example": "opr_maria" }, "expires_at": { "type": "string", "format": "date-time", "example": null } } },
      "Token": { "type": "object", "properties": { "access_token": { "type": "string", "example": "eyJ…" }, "token_type": { "type": "string", "example": "Bearer" }, "expires_in": { "type": "integer", "example": 900 }, "scope": { "type": "string", "example": "org_7f prj_a1" } } },
      "Whoami": { "type": "object", "properties": { "sub": { "type": "string", "example": "opr_maria" }, "org": { "type": "string", "example": "org_7f" }, "projects": { "type": "array", "items": { "type": "object", "properties": { "id": { "type": "string", "example": "prj_a1" }, "role": { "type": "string", "example": "operator" } } } }, "act": { "type": "array", "items": { "type": "string" }, "example": [] } } },
      "Event": { "type": "object", "description": "A structured record of something that happened, in or out.", "properties": { "specversion": { "type": "string", "example": "1.0" }, "type": { "type": "string", "example": "cellplane.task.status.changed" }, "source": { "type": "string", "example": "/prj_a1/workflows/wf_9c" }, "id": { "type": "string", "example": "evt_18420" }, "time": { "type": "string", "format": "date-time" }, "subject": { "type": "string", "example": "t-0217" }, "orgid": { "type": "string", "example": "org_7f" }, "projectid": { "type": "string", "example": "prj_a1" }, "seq": { "type": "integer", "description": "Ledger sequence; use as Last-Event-ID to resume.", "example": 184201 }, "data": { "type": "object", "example": { "from": "running", "to": "stuck", "problem": { "type": "urn:cellplane:problem:tool-timeout" } } } } },
      "LedgerRecord": { "type": "object", "description": "Append-only, hash-chained audit log, partitioned per (org, project).", "properties": { "seq": { "type": "integer", "example": 184201 }, "prev_hash": { "type": "string", "example": "c4a1…" }, "hash": { "type": "string", "example": "9f0e…" }, "kind": { "type": "string", "enum": ["task_spec", "command", "problem", "fix_outcome", "evidence", "config"], "example": "command" }, "at": { "type": "string", "format": "date-time" }, "sub": { "type": "string", "example": "opr_maria" }, "body": { "type": "object" } } },
      "ProblemType": { "type": "object", "description": "Registry entry: URN, HTTP status (or null for task-level), retryable, suggested action, ladder.", "properties": { "type": { "type": "string", "example": "urn:cellplane:problem:tool-timeout" }, "title": { "type": "string", "example": "Tool timeout" }, "status": { "type": "integer", "description": "HTTP status when returned as an API error; null for task-level problems.", "example": null }, "retryable": { "type": "boolean", "example": true }, "suggested_action": { "type": "string", "example": "restart" }, "ladder": { "type": "array", "items": { "type": "string" }, "example": ["restart×1", "reassign×1"] }, "next": { "type": "string", "description": "What a caller should do.", "example": "Restart the task; if it recurs, reassign class." } } }
    }
  },
  "x-problem-types": [
    { "type": "urn:cellplane:problem:schema-invalid", "title": "Schema invalid", "status": 400, "retryable": false, "next": "Body fails JSON Schema 2020-12. errors[] lists JSON Pointers." },
    { "type": "urn:cellplane:problem:token-invalid", "title": "Token invalid", "status": 401, "retryable": true, "next": "Expired, wrong audience, or issuer not bound. Re-authenticate." },
    { "type": "urn:cellplane:problem:budget-ceiling", "title": "Budget ceiling", "status": 402, "retryable": false, "next": "Project or org ceiling would be exceeded. remaining included." },
    { "type": "urn:cellplane:problem:policy-denied", "title": "Policy denied", "status": 403, "retryable": false, "next": "decision and bundle included. Not retryable without a change." },
    { "type": "urn:cellplane:problem:not-in-scope", "title": "Not in scope", "status": 404, "retryable": false, "next": "Missing or foreign; identical by design." },
    { "type": "urn:cellplane:problem:verb-not-applicable", "title": "Verb not applicable", "status": 409, "retryable": false, "next": "allowed[] lists valid verbs for the task's status." },
    { "type": "urn:cellplane:problem:idempotency-conflict", "title": "Idempotency conflict", "status": 409, "retryable": false, "next": "Same key, different body. Use a new key." },
    { "type": "urn:cellplane:problem:binding-unverified", "title": "Binding unverified", "status": 422, "retryable": true, "next": "Run conformance on the named binding." },
    { "type": "urn:cellplane:problem:workflow-paused", "title": "Workflow paused", "status": 423, "retryable": true, "next": "Release the workflow first." },
    { "type": "urn:cellplane:problem:rate-limited", "title": "Rate limited", "status": 429, "retryable": true, "next": "Honour Retry-After." },
    { "type": "urn:cellplane:problem:ledger-integrity", "title": "Ledger integrity", "status": 503, "retryable": false, "next": "Org is read-only until an admin repairs the partition." },
    { "type": "urn:cellplane:problem:adapter-unavailable", "title": "Adapter unavailable", "status": 503, "retryable": true, "next": "boundary named. Other tenants unaffected." },
    { "type": "urn:cellplane:problem:tool-timeout", "title": "Tool timeout", "status": null, "retryable": true, "suggested_action": "restart", "ladder": ["restart×1", "reassign×1"], "next": "Task-level. Ladder restarts, then reassigns; then you." },
    { "type": "urn:cellplane:problem:budget-ceiling-task", "title": "Task over ceiling", "status": null, "retryable": true, "suggested_action": "extend", "ladder": ["extend×1"], "next": "Task-level. one automatic raise, then split or cancel." },
    { "type": "urn:cellplane:problem:no-progress", "title": "No progress", "status": null, "retryable": true, "suggested_action": "nudge", "ladder": ["nudge×2", "escalate×1"], "next": "Task-level. Nudge twice, escalate class once; then redefine." },
    { "type": "urn:cellplane:problem:evaluation-failed", "title": "Evaluation FAIL", "status": null, "retryable": false, "suggested_action": "redefine", "ladder": ["nudge×1"], "next": "Task-level. One nudge quoting the failed clause; then redefine or rollback." },
    { "type": "urn:cellplane:problem:stalled", "title": "Stalled", "status": null, "retryable": true, "suggested_action": "nudge", "ladder": ["nudge×2"], "next": "Task-level. Wait past threshold; nudge, or skip if blocked on a task." },
    { "type": "urn:cellplane:problem:policy-denied-task", "title": "Policy refused", "status": null, "retryable": false, "suggested_action": "grant", "ladder": [], "next": "Approval gate. Grant, return with note, or reject." },
    { "type": "urn:cellplane:problem:approval-required", "title": "Awaiting approval", "status": null, "retryable": false, "suggested_action": "approve", "ladder": [], "next": "Approval gate. Approve, return, or reject." },
    { "type": "urn:cellplane:problem:needs-input", "title": "Needs input", "status": null, "retryable": false, "suggested_action": "answer", "ladder": [], "next": "Agent asked a question. Answer or cancel." }
  ],
  "paths": {}
};

// ---- Paths. Helper keeps each operation to one line of intent; the renderer expands the OpenAPI shape.
const P = (op) => op;
const R = (schema, example) => ({ schema, example });
const OPS = [
  // Auth
  P({ tag: 'Auth', id: 'exchangeToken', method: 'POST', path: '/auth/exchange', scope: 'org', roles: ['system'], summary: 'Exchange an API key or SVID for a scoped token', desc: 'RFC 8693 token exchange. The returned token carries org_id, project_ids and roles derived from the key, with an act chain when a subject token is presented. Expires in ≤ 15 min.', body: { subject_token: 'cpk_live_…', subject_token_type: 'urn:ietf:params:oauth:token-type:access_token', audience: 'cellplane' }, res: 'Token', errors: ['token-invalid', 'rate-limited'], cli: 'cp login --api-key $CP_API_KEY', node: 'const cp = await CellPlane.login({ apiKey })', mock: { access_token: 'eyJ…', token_type: 'Bearer', expires_in: 900, scope: 'org_7f prj_a1' } }),
  P({ tag: 'Auth', id: 'whoami', method: 'GET', path: '/auth/whoami', scope: 'principal', roles: ['viewer', 'operator', 'approver', 'admin'], summary: 'Show the caller\'s scopes and roles', desc: 'Decodes the presented token server-side and returns what it grants. Use it to debug 404 not-in-scope.', res: 'Whoami', errors: ['token-invalid'], cli: 'cp whoami', node: 'await cp.whoami()', mock: { sub: 'opr_maria', org: 'org_7f', projects: [{ id: 'prj_a1', role: 'operator' }], act: [] } }),
  // Orgs
  P({ tag: 'Orgs', id: 'createOrg', method: 'POST', path: '/orgs', scope: 'org', roles: ['platform-admin'], summary: 'Create an organisation', desc: 'Creates the org in provisioning and a Ledger partition with a genesis hash. Bindings are set with the PUT calls below and verified by activate.', body: { name: 'Acme', region: 'eu-west-1', retention_days: 365 }, res: 'Org', errors: ['schema-invalid', 'policy-denied'], cli: 'cp org create Acme --region eu-west-1', node: 'await cp.orgs.create({ name, region })', mock: { id: 'org_7f', name: 'Acme', region: 'eu-west-1', retention_days: 365, status: 'provisioning' } }),
  P({ tag: 'Orgs', id: 'getOrg', method: 'GET', path: '/orgs/{org}', scope: 'org', roles: ['org-admin'], summary: 'Get an organisation and binding states', desc: 'Includes per-binding verification status and the last conformance run id.', params: [['org', 'path', 'org_7f']], res: 'Org', errors: ['not-in-scope'], cli: 'cp org status', node: 'await cp.orgs.get("org_7f")', mock: { id: 'org_7f', status: 'active', bindings: { identity: { status: 'verified', verification: 'run_8812' }, routers: { status: 'verified', verification: 'run_8812' } } } }),
  P({ tag: 'Orgs', id: 'putIdentity', method: 'PUT', path: '/orgs/{org}/identity', scope: 'org', roles: ['org-admin'], summary: 'Bind the identity provider', desc: 'Fetches OIDC discovery, caches JWKS, validates a test token. Done when a token from the issuer validates.', params: [['org', 'path', 'org_7f']], body: 'IdentityBinding', res: 'BindingState', async: true, errors: ['schema-invalid', 'binding-unverified'], cli: 'cp org bind identity --issuer https://id.acme.example', node: 'await org.bind.identity({ issuer, audience })', mock: { status: 'verifying', verification: 'run_8813' } }),
  P({ tag: 'Orgs', id: 'putKeys', method: 'PUT', path: '/orgs/{org}/keys', scope: 'org', roles: ['org-admin'], summary: 'Bind the KMS key for envelope encryption', desc: 'Done when an encrypt/decrypt round-trip of a nonce succeeds with the tenant key.', params: [['org', 'path', 'org_7f']], body: { kms_key_ref: 'arn:aws:kms:eu-west-1:…:key/…' }, res: 'BindingState', async: true, errors: ['binding-unverified'], cli: 'cp org bind keys --kms arn:…', node: 'await org.bind.keys({ kmsKeyRef })', mock: { status: 'verifying', verification: 'run_8814' } }),
  P({ tag: 'Orgs', id: 'putSecret', method: 'PUT', path: '/orgs/{org}/secrets/{urn}', scope: 'org', roles: ['org-admin'], summary: 'Register a secret reference', desc: 'Registers where a secret lives, never its value. Done when resolve returns a non-empty value and the value is absent from every trace.', params: [['org', 'path', 'org_7f'], ['urn', 'path', 'urn:secret:org_7f/litellm/i']], body: { provider: 'vault', path: 'kv/cellplane/litellm/i' }, res: 'BindingState', errors: ['binding-unverified'], cli: 'cp org secret add urn:secret:org_7f/litellm/i --vault kv/cellplane/litellm/i', node: 'await org.secrets.register(urn, { provider, path })', mock: { status: 'verified', verification: 'run_8815' } }),
  P({ tag: 'Orgs', id: 'putStorage', method: 'PUT', path: '/orgs/{org}/storage', scope: 'org', roles: ['org-admin'], summary: 'Bind object storage', desc: 'S3-compatible. Done when PUT/HEAD/GET/DELETE of a probe succeed and ListBucket outside the prefix is denied.', params: [['org', 'path', 'org_7f']], body: 'StorageBinding', res: 'BindingState', async: true, errors: ['binding-unverified'], cli: 'cp org bind storage --bucket acme-cellplane --prefix prod/', node: 'await org.bind.storage({ endpoint, bucket, prefix, credentialRef })', mock: { status: 'verifying', verification: 'run_8816' } }),
  P({ tag: 'Orgs', id: 'putRouters', method: 'PUT', path: '/orgs/{org}/routers', scope: 'org', roles: ['org-admin'], summary: 'Bind model routers per class', desc: 'One OpenAI-compatible endpoint and virtual-key reference per class. Done when a 1-token completion succeeds and an over-ceiling request is refused by the gateway.', params: [['org', 'path', 'org_7f']], body: { bindings: ['RouterBinding'] }, res: 'BindingState', async: true, errors: ['schema-invalid', 'binding-unverified'], cli: 'cp org bind routers routers.yaml', node: 'await org.bind.routers([{ class: "i-", endpoint, keyRef, ceilingPerTask: "4.00", models }])', mock: { status: 'verifying', verification: 'run_8817' } }),
  P({ tag: 'Orgs', id: 'putPolicy', method: 'PUT', path: '/orgs/{org}/policy', scope: 'org', roles: ['org-admin'], summary: 'Bind the policy engine', desc: 'Rego bundle or bring-your-own decision endpoint. Done when the bundle compiles and the canonical over-ceiling test returns deny.', params: [['org', 'path', 'org_7f']], body: 'PolicyBinding', res: 'BindingState', async: true, errors: ['binding-unverified'], cli: 'cp org bind policy --bundle https://…/cellplane.tar.gz', node: 'await org.bind.policy({ engine: "opa", bundleUrl })', mock: { status: 'verifying', verification: 'run_8818' } }),
  P({ tag: 'Orgs', id: 'activateOrg', method: 'POST', path: '/orgs/{org}/activate', scope: 'org', roles: ['org-admin'], summary: 'Run conformance and activate', desc: 'Runs the full suite across all bindings. Flips status to active only when every check is green; writes an evidence record.', params: [['org', 'path', 'org_7f']], res: 'Org', async: true, errors: ['binding-unverified'], cli: 'cp org activate', node: 'await org.activate()', mock: { id: 'org_7f', status: 'active' } }),
  P({ tag: 'Orgs', id: 'exportOrg', method: 'POST', path: '/orgs/{org}/export', scope: 'org', roles: ['org-admin'], summary: 'Export ledger partitions and config', desc: 'Signed tarball to the org storage binding with a verification script. Required before delete.', params: [['org', 'path', 'org_7f']], res: { job: 'job_…', location: 's3://…' }, async: true, errors: ['adapter-unavailable'], cli: 'cp org export', node: 'await org.export()', mock: { job: 'job_41', location: 's3://acme-cellplane/prod/exports/2026-09-10.tar.zst' } }),
  P({ tag: 'Orgs', id: 'deleteOrg', method: 'DELETE', path: '/orgs/{org}', scope: 'org', roles: ['org-admin'], summary: 'Delete an organisation', desc: 'Refused unless an export newer than the last write exists. Drops partitions, schedules key destruction, writes a tombstone.', params: [['org', 'path', 'org_7f']], res: { status: 'deleting' }, errors: ['policy-denied'], cli: 'cp org delete --confirm', node: 'await org.delete()', mock: { status: 'deleting' } }),
  // Projects
  P({ tag: 'Projects', id: 'createWorkspace', method: 'POST', path: '/projects', scope: 'org', roles: ['org-admin', 'admin'], summary: 'Create a project (project)', desc: 'A project owns Task specifications, workflows, playbooks and a budget. The cp CLI calls this "sandbox".', body: { name: 'vendor-review', default_class: 'i-', budget: { ceiling: '40.00', per_task: '0.60', alert_at: 0.8 } }, res: 'Project', errors: ['schema-invalid', 'policy-denied'], cli: 'cp project create vendor-review --budget 40 --class i-', node: 'await cp.projects.create({ name, budget: 40, defaultClass: "i-" })', mock: { id: 'prj_a1', org: 'org_7f', name: 'vendor-review', default_class: 'i-', budget: { ceiling: '40.00', per_task: '0.60', spent: '0.00', alert_at: 0.8 } } }),
  P({ tag: 'Projects', id: 'listWorkspaces', method: 'GET', path: '/projects', scope: 'org', roles: ['viewer'], summary: 'List projects the caller can see', params: [['limit', 'query', 50], ['cursor', 'query', null]], res: { items: ['Project'], next_cursor: null }, errors: [], cli: 'cp project list', node: 'await cp.projects.list()', mock: { items: [{ id: 'prj_a1', name: 'vendor-review' }], next_cursor: null } }),
  P({ tag: 'Projects', id: 'putBudget', method: 'PUT', path: '/projects/{project}/budget', scope: 'ws', roles: ['admin'], summary: 'Set project budget', desc: 'Ceiling and per-task default. Enforced at the gateway virtual key and re-checked by policy before dispatch.', params: [['ws', 'path', 'prj_a1']], body: { ceiling: '40.00', per_task: '0.60', alert_at: 0.8 }, res: 'Budget', errors: ['schema-invalid', 'policy-denied'], cli: 'cp budget set --project vendor-review --per-task 0.60 --alert 80%', node: 'await prj.budget.set({ perCell: 0.60, alertAt: 0.8 })', mock: { ceiling: '40.00', per_task: '0.60', spent: '12.40', alert_at: 0.8 } }),
  P({ tag: 'Projects', id: 'putMembership', method: 'PUT', path: '/projects/{project}/members/{sub}', scope: 'ws', roles: ['admin'], summary: 'Grant or change a member role', desc: 'Roles: viewer, operator, approver, admin. Approvers cannot approve tasks whose Task specification they authored.', params: [['ws', 'path', 'prj_a1'], ['sub', 'path', 'opr_li']], body: { role: 'operator', expires_at: null }, res: 'Membership', errors: ['policy-denied'], cli: 'cp project grant opr_li operator', node: 'await prj.members.set("opr_li", { role: "operator" })', mock: { sub: 'opr_li', role: 'operator', granted_by: 'opr_maria', expires_at: null } }),
  P({ tag: 'Projects', id: 'deleteMembership', method: 'DELETE', path: '/projects/{project}/members/{sub}', scope: 'ws', roles: ['admin'], summary: 'Revoke a member', params: [['ws', 'path', 'prj_a1'], ['sub', 'path', 'opr_li']], res: { removed: true }, errors: ['policy-denied'], cli: 'cp project revoke opr_li', node: 'await prj.members.remove("opr_li")', mock: { removed: true } }),
  // Task specifications
  P({ tag: 'TaskSpecs', id: 'createTaskSpec', method: 'POST', path: '/task-specs', scope: 'ws', roles: ['admin', 'operator'], summary: 'Create a Task specification and price its plan', desc: 'Validates against JSON Schema 2020-12, stores revision 1, runs the Planner. Returns plan and cost. Nothing is dispatched. A template supplies steps, dod and class; you supply intent and inputs.', body: { intent: 'Summarise one vendor\'s public security docs into the posture template, citing every claim', template: 'research', class: 'b-', inputs: [{ vendor: 'acme' }, { vendor: 'globex' }] }, res: { task_spec: 'TaskSpec', plan: 'Plan' }, errors: ['schema-invalid', 'budget-ceiling', 'policy-denied'], cli: 'cp spec "Summarise each vendor\'s security docs…" --template research --inputs vendors.csv', node: 'const plan = await prj.plan({ intent, template: "research", inputs })', mock: { task_spec: { id: 'spec_8f1', rev: 1, template: 'research', class: 'b-' }, plan: { units: 15, cost: { estimate: '3.30', per_task: '0.22', ceiling: '9.00', currency: 'USD' } } } }),
  P({ tag: 'TaskSpecs', id: 'getTaskSpec', method: 'GET', path: '/task-specs/{doc}', scope: 'ws', roles: ['viewer'], summary: 'Get a Task specification (latest revision)', params: [['doc', 'path', 'spec_8f1'], ['rev', 'query', null]], res: 'TaskSpec', errors: ['not-in-scope'], cli: 'cp spec show spec_8f1', node: 'await prj.taskSpecs.get("spec_8f1")', mock: { id: 'spec_8f1', rev: 2, parent_rev: 1, template: 'research', class: 'b-', acceptance_criteria: ['every claim carries a source URL that resolves', 'template fields populated', '≤ 600 words'] } }),
  P({ tag: 'TaskSpecs', id: 'reviseTaskSpec', method: 'POST', path: '/task-specs/{doc}/revisions', scope: 'ws', roles: ['admin', 'operator'], summary: 'Create a new revision', desc: 'Immutable; parent_rev recorded. Running tasks keep their revision. Redefine moves a task to the new one.', params: [['doc', 'path', 'spec_8f1']], body: { acceptance_criteria: ['every claim carries a source URL that resolves', 'template fields populated', '≤ 600 words'] }, res: 'TaskSpec', errors: ['schema-invalid'], cli: 'cp spec edit spec_8f1', node: 'await doc.revise({ acceptance_criteria })', mock: { id: 'spec_8f1', rev: 2, parent_rev: 1 } }),
  P({ tag: 'TaskSpecs', id: 'revertTaskSpec', method: 'POST', path: '/task-specs/{doc}/revisions/{rev}/revert', scope: 'ws', roles: ['admin'], summary: 'Revert to a prior revision', desc: 'Creates a new revision equal to the prior content. The chain stays intact.', params: [['doc', 'path', 'spec_8f1'], ['rev', 'path', 1]], res: 'TaskSpec', errors: ['not-in-scope'], cli: 'cp spec revert spec_8f1 --to 1', node: 'await doc.revert(1)', mock: { id: 'spec_8f1', rev: 3, parent_rev: 1 } }),
  P({ tag: 'TaskSpecs', id: 'listTemplates', method: 'GET', path: '/templates', scope: 'ws', roles: ['viewer'], summary: 'List templates (Task specification templates)', desc: 'Platform templates plus those published in the org. Fork one with cp template fork.', res: { items: [{ name: 'research', steps: 4, class: 'b-', ceiling_per_task: '0.60' }] }, errors: [], cli: 'cp template list', node: 'await cp.templates.list()', mock: { items: [{ name: 'research', steps: 4, class: 'b-' }, { name: 'refactor', steps: 5, class: 'cli-' }, { name: 'review', steps: 5, class: 'i-' }] } }),
  // Workflows
  P({ tag: 'Workflows', id: 'createWorkflow', method: 'POST', path: '/workflows', scope: 'ws', roles: ['operator', 'admin'], summary: 'Bind a Task specification revision to an intake', desc: 'Returns the webhook URL and signing-secret reference for push intakes. Schedules take an RFC 5545 rrule.', body: { task_spec: 'spec_8f1', rev: 1, intake: 'http' }, res: 'Workflow', errors: ['schema-invalid', 'policy-denied'], cli: 'cp run plan_8f1  # creates the workflow and dispatches', node: 'const run = await plan.run()', mock: { id: 'wf_9c', task_spec: 'spec_8f1', rev: 1, intake: 'http', paused: false, webhook: 'https://cellplane.example/v1/intake/wf_9c', secret_ref: 'urn:secret:org_7f/intake/wf_9c', tasks: 0 } }),
  P({ tag: 'Workflows', id: 'dispatch', method: 'POST', path: '/workflows/{wf}/dispatch', scope: 'ws', roles: ['operator', 'admin'], summary: 'Dispatch tasks', desc: 'Creates count tasks, each with an idempotency key derived from (workflow, Idempotency-Key, index). Replays return the same tasks. Refused when the workflow is paused or a ceiling would be exceeded.', params: [['wf', 'path', 'wf_9c']], body: { count: 15, inputs: [{ vendor: 'acme' }] }, res: { tasks: ['t-1001'], ceiling_total: '9.00' }, errors: ['budget-ceiling', 'workflow-paused', 'binding-unverified', 'idempotency-conflict'], cli: 'cp run plan_8f1 --tasks 15', node: 'await run.dispatch({ count: 15 })', mock: { tasks: ['t-1001', 't-1002', 't-1003'], ceiling_total: '9.00' } }),
  P({ tag: 'Workflows', id: 'pauseWorkflow', method: 'POST', path: '/workflows/{wf}/pause', scope: 'ws', roles: ['operator', 'admin'], summary: 'Pause dispatch', desc: 'Running tasks finish their step. Recorded as a Ledger command.', params: [['wf', 'path', 'wf_9c']], res: 'Workflow', errors: ['not-in-scope'], cli: 'cp pause wf_9c', node: 'await run.hold()', mock: { id: 'wf_9c', paused: true } }),
  P({ tag: 'Workflows', id: 'resumeWorkflow', method: 'POST', path: '/workflows/{wf}/resume', scope: 'ws', roles: ['operator', 'admin'], summary: 'Resume dispatch', params: [['wf', 'path', 'wf_9c']], res: 'Workflow', errors: ['not-in-scope'], cli: 'cp resume wf_9c', node: 'await run.release()', mock: { id: 'wf_9c', paused: false } }),
  P({ tag: 'Workflows', id: 'cloneWorkflow', method: 'POST', path: '/workflows/{wf}/clone', scope: 'ws', roles: ['operator', 'admin'], summary: 'Clone a workflow', desc: 'Same Task specification revision, optional overrides for intake, class and count.', params: [['wf', 'path', 'wf_9c']], body: { name: 'vendor-review (copy)', count: 12 }, res: 'Workflow', errors: [], cli: 'cp clone wf_9c --tasks 12', node: 'await run.clone({ count: 12 })', mock: { id: 'wf_9d', task_spec: 'spec_8f1', rev: 1 } }),
  P({ tag: 'Workflows', id: 'listWorkflows', method: 'GET', path: '/workflows', scope: 'ws', roles: ['viewer'], summary: 'List workflows with state summary', params: [['status', 'query', null], ['limit', 'query', 50]], res: { items: ['Workflow'], next_cursor: null }, errors: [], cli: 'cp list', node: 'await prj.workflows.list()', mock: { items: [{ id: 'wf_9c', tasks: 15, summary: { running: 11, waiting: 2, stuck: 1, done: 1 } }], next_cursor: null } }),
  P({ tag: 'Workflows', id: 'workflowResults', method: 'GET', path: '/workflows/{wf}/results', scope: 'ws', roles: ['viewer'], summary: 'List completed artifacts', desc: 'Digest, content type, producing task and provenance attestation per artifact. Bodies live in the org storage binding.', params: [['wf', 'path', 'wf_9c']], res: { items: [{ task: 't-1001', name: 'acme.posture.md', digest: 'sha256:…', location: 's3://…' }] }, errors: [], cli: 'cp results wf_9c --out ./posture/', node: 'await run.results().download("./posture/")', mock: { items: [{ task: 't-1001', name: 'acme.posture.md', digest: 'sha256:9f0e…', location: 's3://acme-cellplane/prod/prj_a1/t-1001/acme.posture.md' }] } }),
  // Tasks
  P({ tag: 'Tasks', id: 'listTasks', method: 'GET', path: '/tasks', scope: 'ws', roles: ['viewer'], summary: 'List tasks (the Tasks and Board views)', desc: 'Current-state projection from the Ledger joined with the open problem and spend. groupBy=stage returns Board columns.', params: [['workflow', 'query', 'wf_9c'], ['substate', 'query', 'blocked'], ['q', 'query', null], ['groupBy', 'query', null], ['limit', 'query', 100]], res: { items: ['Task'], next_cursor: null }, errors: [], cli: 'cp tasks --substate blocked', node: 'await prj.tasks.list({ status: "stuck" })', mock: { items: [{ id: 't-0217', status: 'working', substate: 'blocked', stage: 'Build', model: 'claude-code-cli', budget: { spent: '3.10', ceiling: '6.00' }, problem: { type: 'urn:cellplane:problem:evaluation-failed', title: 'Evaluation FAIL ×2', suggested_action: 'redefine' } }], next_cursor: null } }),
  P({ tag: 'Tasks', id: 'getTask', method: 'GET', path: '/tasks/{task}', scope: 'task', roles: ['viewer'], summary: 'Get a task with its Task specification, plan position and ladder', params: [['task', 'path', 't-0217']], res: 'Task', errors: ['not-in-scope'], cli: 'cp open t-0217', node: 'await prj.tasks.get("t-0217")', mock: { id: 't-0217', status: 'working', substate: 'blocked', step_idx: 2, stage: 'Build', model: 'claude-code-cli', budget: { spent: '3.10', ceiling: '6.00' }, problem: { type: 'urn:cellplane:problem:evaluation-failed', failed_clause: 'no new @ts-ignore or any', suggested_action: 'redefine' }, exhausted: false } }),
  P({ tag: 'Tasks', id: 'taskEvents', method: 'GET', path: '/tasks/{task}/events', scope: 'task', roles: ['viewer'], summary: 'Timeline of a task', desc: 'Span events from the trace store filtered by task.id, merged with Ledger commands.', params: [['task', 'path', 't-0217'], ['limit', 'query', 50]], res: { items: ['Event'] }, errors: [], cli: 'cp log t-0217', node: 'await task.events()', mock: { items: [{ type: 'cellplane.task.status.changed', subject: 't-0217', seq: 184201, data: { from: 'working', to: 'working', substate: 'blocked' } }] } }),
  P({ tag: 'Tasks', id: 'command', method: 'POST', path: '/tasks/{task}/commands', scope: 'task', roles: ['operator', 'approver'], summary: 'Apply a command to one task', desc: 'Validates the verb against the task status, asks Policy, stamps actor and idempotency, then routes. approve/grant/reject/return require approver. Returns policy decision and effects.', params: [['task', 'path', 't-0217']], body: { verb: 'extend', args: { pct: 50 } }, res: 'Command', errors: ['verb-not-applicable', 'policy-denied', 'idempotency-conflict'], cli: 'cp fix t-0217 --raise-ceiling 50', node: 'await task.raiseCeiling({ pct: 50 })', mock: { id: 'cmd_3a', verb: 'extend', tasks: ['t-0217'], actor: 'opr_maria', policy: { decision: 'allow', engine: 'opa', bundle: 'org_7f/prj_a1@v12' }, effects: ['budget.ceiling:9.00', 'dispatch.resume'], compensable_until: '2026-09-10T14:02:19Z' } }),
  P({ tag: 'Tasks', id: 'bulkCommand', method: 'POST', path: '/commands', scope: 'ws', roles: ['operator', 'approver'], summary: 'Apply a command to many tasks', desc: 'Same body with tasks[]. One result per task. Destructive verbs on more than the policy threshold require a second approver.', body: { verb: 'nudge', tasks: ['t-0217', 't-0231'] }, res: { results: ['Command'] }, errors: ['verb-not-applicable', 'policy-denied'], cli: 'cp fix --all-stuck --nudge', node: 'await prj.tasks.command({ verb: "nudge", tasks })', mock: { results: [{ id: 'cmd_3b', verb: 'nudge', tasks: ['t-0217'], policy: { decision: 'allow' } }, { id: 'cmd_3c', verb: 'nudge', tasks: ['t-0231'], policy: { decision: 'allow' } }] } }),
  P({ tag: 'Tasks', id: 'compensateCommand', method: 'POST', path: '/commands/{cmd}/compensate', scope: 'ws', roles: ['operator'], summary: 'Compensate a command within its window', desc: 'Compensating command. Refused for cancel and reject. Marks compensated_by on the original.', params: [['cmd', 'path', 'cmd_3a']], res: 'Command', errors: ['verb-not-applicable'], cli: 'cp compensate', node: 'await cmd.compensate()', mock: { id: 'cmd_3d', verb: 'compensate', tasks: ['t-0217'], effects: ['budget.ceiling:6.00'] } }),
  // Playbooks
  P({ tag: 'Playbooks', id: 'listPlaybooks', method: 'GET', path: '/playbooks', scope: 'ws', roles: ['viewer'], summary: 'List recovery ladders with outcomes', res: { items: ['Playbook'] }, errors: [], cli: 'cp playbooks', node: 'await prj.playbooks.list()', mock: { items: [{ problem_type: 'urn:cellplane:problem:tool-timeout', rungs: [{ verb: 'restart', max: 1 }, { verb: 'reassign', max: 1 }], human_verb: 'reassign', stats: { tried: 42, resolved_pct: 71, automatic_pct: 64 } }] } }),
  P({ tag: 'Playbooks', id: 'putPlaybook', method: 'PUT', path: '/playbooks/{type}', scope: 'ws', roles: ['admin'], summary: 'Set the ladder for a problem type', desc: 'Rungs fire in order, each up to max times per task, under actor playbook:<type>/<verb>. Ladders never edit a Task specification.', params: [['type', 'path', 'tool-timeout']], body: { rungs: [{ verb: 'restart', max: 1 }, { verb: 'reassign', max: 1 }], human_verb: 'reassign' }, res: 'Playbook', errors: ['schema-invalid', 'policy-denied'], cli: 'cp playbook set tool-timeout --rungs restart:1,reassign:1', node: 'await prj.playbooks.set("tool-timeout", { rungs })', mock: { problem_type: 'urn:cellplane:problem:tool-timeout', rungs: [{ verb: 'restart', max: 1 }, { verb: 'reassign', max: 1 }], human_verb: 'reassign' } }),
  P({ tag: 'Playbooks', id: 'togglePlaybook', method: 'PUT', path: '/playbooks/{type}/workflows/{wf}', scope: 'ws', roles: ['operator', 'admin'], summary: 'Enable or disable self-healing per workflow', params: [['type', 'path', 'tool-timeout'], ['wf', 'path', 'wf_9c']], body: { enabled: false }, res: { enabled: false }, errors: [], cli: 'cp playbook off tool-timeout --workflow wf_9c', node: 'await prj.playbooks.toggle("tool-timeout", "wf_9c", false)', mock: { enabled: false } }),
  // Recommendations
  P({ tag: 'Recommendations', id: 'listRecommendations', method: 'GET', path: '/recommendations', scope: 'ws', roles: ['viewer'], summary: 'List recurring problems with proposals', desc: 'Derived from Problem and FixOutcome records over the window. Includes before/after recurrence for applied recommendations.', params: [['window', 'query', '7d'], ['state', 'query', 'proposed']], res: { items: ['Recommendation'] }, errors: [], cli: 'cp recommendations', node: 'await prj.recommendations()', mock: { items: [{ id: 'rec_1', problem_type: 'urn:cellplane:problem:tool-timeout', workflow: 'wf_9c', count: 4, cost_lost: '1.84', proposal: { target: 'dispatch.config', text: 'Raise per-tool ceiling to 120s for this workflow' }, state: 'proposed' }] } }),
  P({ tag: 'Recommendations', id: 'applyRecommendation', method: 'POST', path: '/recommendations/{fnd}/apply', scope: 'ws', roles: ['admin'], summary: 'Apply a proposal', desc: 'Writes a Task specification revision or dispatch-config change, policy-checked, and starts before/after measurement.', params: [['fnd', 'path', 'rec_1']], res: 'Recommendation', errors: ['policy-denied'], cli: 'cp recommendations apply rec_1', node: 'await recommendation.apply()', mock: { id: 'rec_1', state: 'applied', applied_rev: 2, before: 4, after: 0 } }),
  P({ tag: 'Recommendations', id: 'dismissRecommendation', method: 'POST', path: '/recommendations/{fnd}/dismiss', scope: 'ws', roles: ['operator', 'admin'], summary: 'Dismiss a proposal for the window', params: [['fnd', 'path', 'rec_1']], res: 'Recommendation', errors: [], cli: 'cp recommendations dismiss rec_1', node: 'await recommendation.dismiss()', mock: { id: 'rec_1', state: 'dismissed' } }),
  // Streams & intake
  P({ tag: 'EventStreams', id: 'stream', method: 'GET', path: '/event-stream', scope: 'ws', roles: ['viewer'], summary: 'Subscribe to project events (SSE)', desc: 'CloudEvents, one per state transition. Send Last-Event-ID = seq to resume without loss. Filters narrow server-side.', params: [['workflow', 'query', 'wf_9c'], ['task', 'query', null], ['Last-Event-ID', 'header', 184200]], res: 'Event', sse: true, errors: ['rate-limited'], cli: 'cp watch wf_9c', node: 'for await (const ev of run.watch()) …', mock: { specversion: '1.0', type: 'cellplane.task.status.changed', subject: 't-0217', seq: 184201, orgid: 'org_7f', projectid: 'prj_a1', data: { from: 'working', to: 'working', substate: 'blocked', problem: { type: 'urn:cellplane:problem:tool-timeout' } } } }),
  P({ tag: 'EventStreams', id: 'orgStream', method: 'GET', path: '/orgs/{org}/event-stream', scope: 'org', roles: ['org-admin'], summary: 'Subscribe to org events (SSE)', desc: 'Binding verifications, memberships, policy bundle loads, retention jobs.', params: [['org', 'path', 'org_7f']], res: 'Event', sse: true, errors: [], cli: 'cp org watch', node: 'for await (const ev of org.watch()) …', mock: { type: 'cellplane.org.routers.verified', data: { class: 'i-', ceiling_enforced: true } } }),
  P({ tag: 'EventStreams', id: 'intake', method: 'POST', path: '/intake/{wf}', scope: 'ws', roles: ['signed-webhook'], summary: 'Push work into a workflow', desc: 'Signed CloudEvent. Its id becomes the dispatch idempotency root; a duplicate id returns 200 with the prior tasks. Signature uses the workflow secret reference.', params: [['wf', 'path', 'wf_9c'], ['X-Signature', 'header', 'sha256=…']], body: { specversion: '1.0', type: 'com.acme.vendor.added', source: '/vendors', id: 'evt_a91', data: { vendor: 'initech' } }, res: { tasks: ['t-1016'] }, errors: ['schema-invalid', 'workflow-paused', 'token-invalid'], cli: 'cp intake wf_9c event.json', node: 'await run.intake(event)', mock: { tasks: ['t-1016'] } }),
  // Ledger
  P({ tag: 'Ledger', id: 'readLedger', method: 'GET', path: '/ledger', scope: 'ws', roles: ['viewer'], summary: 'Read the hash chain', desc: 'Range read by seq and kind. Includes hashes so a tenant can verify with the published script.', params: [['from_seq', 'query', 184000], ['kinds', 'query', 'command,problem'], ['limit', 'query', 200]], res: { items: ['LedgerRecord'], head: { seq: 184201, hash: '9f0e…' } }, errors: [], cli: 'cp ledger --from 184000', node: 'await prj.ledger.read({ fromSeq })', mock: { items: [{ seq: 184201, prev_hash: 'c4a1…', hash: '9f0e…', kind: 'command', sub: 'opr_maria', body: { verb: 'extend', tasks: ['t-0217'] } }], head: { seq: 184201, hash: '9f0e…' } } }),
  P({ tag: 'Ledger', id: 'verifyLedger', method: 'POST', path: '/ledger/verify', scope: 'ws', roles: ['viewer'], summary: 'Verify chain integrity', desc: 'Server-side walk; returns the first bad seq if any. The same check the boot sequence runs.', res: { ok: true, checked: 184201, first_bad_seq: null }, errors: ['ledger-integrity'], cli: 'cp ledger verify', node: 'await prj.ledger.verify()', mock: { ok: true, checked: 184201, first_bad_seq: null } }),
  // Problem types
  P({ tag: 'ProblemTypes', id: 'listProblemTypes', method: 'GET', path: '/problem-types', scope: 'principal', roles: ['viewer'], summary: 'List the problem-type registry', desc: 'API errors and task-level problems share one registry. Each carries status, retryable, suggested action and ladder.', res: { items: ['ProblemType'] }, errors: [], cli: 'cp problems', node: 'await cp.problemTypes.list()', mock: { items: [{ type: 'urn:cellplane:problem:tool-timeout', title: 'Tool timeout', retryable: true, suggested_action: 'restart', ladder: ['restart×1', 'reassign×1'] }] } }),
  P({ tag: 'ProblemTypes', id: 'getProblemType', method: 'GET', path: '/problem-types/{name}', scope: 'principal', roles: ['viewer'], summary: 'Resolve one problem type', params: [['name', 'path', 'tool-timeout']], res: 'ProblemType', errors: ['not-in-scope'], cli: 'cp problems tool-timeout', node: 'await cp.problemTypes.get("tool-timeout")', mock: { type: 'urn:cellplane:problem:tool-timeout', title: 'Tool timeout', status: null, retryable: true, suggested_action: 'restart', ladder: ['restart×1', 'reassign×1'], next: 'Restart the task; if it recurs, reassign class.' } })
];
export const TAGS = [['Auth', 'Tokens, exchange and scopes.'], ['Orgs', 'Organisations and their bindings: identity, keys, secrets, storage, routers, policy.'], ['Projects', 'Sandboxes: budgets and memberships.'], ['TaskSpecs', 'Declared intent, acceptance criteria, steps; priced by the Planner before anything runs.'], ['Workflows', 'A Task specification revision bound to an intake; dispatch, hold, clone, results.'], ['Tasks', 'One agent run each. Read models and the user command set.'], ['Playbooks', 'Recovery ladders per problem type.'], ['Recommendations', 'Recurring problems and the Task specification edits that remove them.'], ['EventStreams', 'SSE out, signed CloudEvents in.'], ['Ledger', 'The hash chain, readable and verifiable.'], ['ProblemTypes', 'The registry behind every error and every stuck reason.']];
export { OPS };
