#!/usr/bin/env python3
"""Write docs/examples/index.md: every live example area by the four doors, measured from disk.

Discovery, not a hardcoded list. This file used to carry
`AREAS = ["run", "ask", "watch", "steer", "progress", "done", "improve"]`, and when those seven were
archived on 2026-09-09 it kept writing an index of work that no longer existed -- one of the seven
artifacts STATUS row 86 counts. A list that globs cannot go stale the same way: an area under
examples/reference/ appears the moment it exists, and a planned one that nobody has built is shown
as planned rather than omitted.
"""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOORS = ["human", "event", "schedule", "external"]
PRINCIPLES = ROOT / "docs" / "reference" / "build-principles.json"


def areas() -> list:
    """(name, path or None) for every planned area, plus end-to-end, in the owner's order."""
    planned = json.loads(PRINCIPLES.read_text())["example_areas"] if PRINCIPLES.is_file() else []
    out = [(n, ROOT / "examples" / "reference" / n) for n in planned]
    if (ROOT / "examples" / "end-to-end" / "README.md").is_file():
        out.append(("end-to-end", ROOT / "examples" / "end-to-end"))
    return out


def last(cmd: str) -> str:
    r = subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True, text=True)
    o = (r.stdout + r.stderr).strip().splitlines()
    return o[-1] if o else f"exit {r.returncode}"


def main() -> int:
    found = areas()
    L = ["# Examples: the future state as its user meets it", "",
         "Generated by `tools/examples_index.py` from what is on disk. One area per reference-model "
         "area, each through the four doors; `bash examples/reference/<area>/test.sh` is the visible "
         "check and `docs/night/hidden/<area>.sh` the hidden one. `end-to-end` is the reference walk "
         "across all of them, not one of them. The seven journey areas this replaced are in "
         "`examples/archived/`, kept as evidence.", "",
         "| Area | " + " | ".join(DOORS) + " | Visible check | Hidden check | README |",
         "|---|" + "---|" * (len(DOORS) + 3)]
    built = 0
    for name, d in found:
        rel = d.relative_to(ROOT)
        if not (d / "README.md").is_file():
            L.append(f"| {name} | " + " | ".join("-" for _ in DOORS)
                     + " | planned, not built | - | - |")
            continue
        built += 1
        doors = ["yes" if (d / "entries" / f"{x}.json").is_file() else "no" for x in DOORS]
        vis = last(f"bash {rel}/test.sh") if (d / "test.sh").is_file() else "no test.sh"
        hid_p = ROOT / "docs" / "night" / "hidden" / f"{name}.sh"
        hid = last(f"bash docs/night/hidden/{name}.sh") if hid_p.is_file() else "-"
        L.append(f"| {name} | " + " | ".join(doors) + f" | {vis} | {hid} | `{rel}/README.md` |")
    L += ["", f"{built} of {len(found)} built."]
    (ROOT / "docs" / "examples" / "index.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[6:]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
