#!/usr/bin/env python3
"""Write docs/examples/index.md: the seven areas by the four doors, from examples/<area>/ on disk (STATUS row 75)."""
import json, subprocess, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
AREAS = ["run", "ask", "watch", "steer", "progress", "done", "improve"]
DOORS = ["human", "event", "schedule", "external"]
L = ["# Examples: the future state as its user meets it", "", "Generated by `tools/examples_index.py`. One example per area, each through the four doors; `bash examples/<area>/test.sh` is the visible check, `docs/night/hidden/<area>.sh` the hidden one.", "",
     "| Area | " + " | ".join(DOORS) + " | Visible check | Hidden check | README |", "|---|" + "---|" * (len(DOORS) + 3)]
for a in AREAS:
    d = ROOT / "examples" / a
    if not (d / "README.md").is_file():
        L.append(f"| {a} | " + " | ".join("-" for _ in DOORS) + " | not built | - | - |"); continue
    doors = ["yes" if (d / "entries" / f"{x}.json").is_file() else "no" for x in DOORS]
    def last(cmd):
        r = subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True, text=True); o = (r.stdout + r.stderr).strip().splitlines(); return o[-1] if o else f"exit {r.returncode}"
    vis = last(f"bash examples/{a}/test.sh") if (d / "test.sh").is_file() else "no test.sh"
    hid = last(f"bash docs/night/hidden/{a}.sh") if (ROOT / "docs" / "night" / "hidden" / f"{a}.sh").is_file() else "-"
    L.append(f"| {a} | " + " | ".join(doors) + f" | {vis} | {hid} | `examples/{a}/README.md` |")
(ROOT / "docs" / "examples" / "index.md").write_text("\n".join(L) + "\n")
print("\n".join(L[-len(AREAS):]))
