#!/usr/bin/env python3
"""Write docs/reference/knowledge-pool.md: how much knowledge stands behind each card.

Read-only. Every figure comes from a citation actually present in a card profile, so this is a
join and not a score - no keyword matching, no similarity, nothing to tune.

Three grades, named for what they mean rather than for the field they came from, because
"search-only" reads as "no work was done" when it means the opposite: a card with citations
whose sources were never read on the page.

  documented    a profile exists, and 3+ of its citations rest on a page someone fetched
  unread        a profile exists with real citations, but the sources behind them are search
                snippets - nobody opened the page
  undocumented  no profile: nothing has been written down for this card at all
"""
import collections
import json
import glob
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference" / "knowledge-pool.md"
FETCHED_BAR = 3


def load():
    rec = {}
    for line in (ROOT / "kb" / "research.jsonl").read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            rec[r["id"]] = r
    model = json.loads((ROOT / "docs" / "reference" / "reference-model.json").read_text())
    prof = {os.path.basename(p).replace(".json", ""): json.loads(Path(p).read_text())
            for p in glob.glob(str(ROOT / "docs" / "reference" / "cards" / "*.json"))}
    lens = collections.Counter(r["lens"] for r in rec.values())
    return rec, model, prof, lens


def citations(d):
    out = []
    def walk(o):
        if isinstance(o, dict):
            for e in (o.get("evidence") or []):
                if isinstance(e, dict) and "id" in e:
                    out.append(e["id"])
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)
    walk(d)
    return out


def main():
    rec, model, prof, lens = load()
    rows = []
    for area in model["areas"]:
        tag = area["num"][:-1] if area["num"] else area["region"]
        for c in area["cards"]:
            key, addr = f"{tag}-{c['order']}", f"{tag}.{c['order']}"
            d = prof.get(key)
            cites = citations(d) if d else []
            x = [i for i in cites if i.startswith("X-")]
            fetched = sum(1 for i in x if rec.get(i, {}).get("status") == "fetched")
            grade = ("undocumented" if not d else
                     "documented" if fetched >= FETCHED_BAR else "unread")
            rows.append({
                "area": area["title"], "addr": addr, "card": c["name"],
                "status": c["status"], "grade": grade, "cites": len(cites),
                "fetched": fetched,
                "direct": sum(1 for i in x if i.startswith("X-refmodel")),
                "prior": sum(1 for i in x if not i.startswith("X-refmodel")),
                "repo": len(cites) - len(x),
                "lens": sum(v for k, v in lens.items() if k.startswith(f"refmodel-{key}-")),
                "gaps": len(d.get("gaps", [])) if d else 0,
            })

    tot = collections.Counter(r["grade"] for r in rows)
    L = []
    L.append("# Knowledge pool — what stands behind each card\n")
    L.append(f"Generated by `python3 tools/knowledge_pool.py` from citations present in "
             f"`docs/reference/cards/*.json`. Every number is a join against a real record id, "
             f"not a score. Re-run it rather than trusting these figures later.\n")
    L.append("## What the grades mean\n")
    L.append("| Grade | Meaning |")
    L.append("|---|---|")
    L.append(f"| **documented** | A profile exists and {FETCHED_BAR}+ of its citations rest on a page "
             "someone actually fetched and read. |")
    L.append("| **unread** | A profile exists with real, verified citations — often 8 to 17 of them — "
             "but the research behind them is search-result snippets. Nobody opened the page. "
             "This is *not* an absence of work; it is work at a weaker evidence grade. |")
    L.append("| **undocumented** | No profile. Nothing has been written down for this card. |")
    L.append("")
    L.append(f"**{tot['documented']} documented · {tot['unread']} unread · "
             f"{tot['undocumented']} undocumented**, of 40 cards.\n")

    L.append("## Two bodies of research, and where each landed\n")
    direct = sum(r["direct"] for r in rows)
    prior = sum(r["prior"] for r in rows)
    repo = sum(r["repo"] for r in rows)
    L.append(f"- **direct** — {direct} citations to research commissioned for the reference model "
             "(`X-refmodel-*` lenses, fetched pages)")
    L.append(f"- **prior** — {prior} citations to the research corpus that existed before it "
             "(other `X-` lenses, search snippets)")
    L.append(f"- **repo** — {repo} citations to this repo's own documents "
             "(`F-` facts, `T-` targets, `A-` architecture, `REF-` reference)\n")

    L.append("## By card\n")
    L.append("`cites` counts every verified citation. `fetch` is how many rest on a fetched page. "
             "`lens` is the size of that card's dedicated research lens, if it has one.\n")
    cur = None
    for r in rows:
        if r["area"] != cur:
            cur = r["area"]
            L.append(f"\n### {cur}\n")
            L.append("| Card | Model | Grade | cites | fetch | direct | prior | repo | lens | gaps |")
            L.append("|---|---|---|---:|---:|---:|---:|---:|---:|---:|")
        L.append(f"| {r['addr']} {r['card']} | {r['status']} | {r['grade']} | {r['cites']} | "
                 f"{r['fetched']} | {r['direct']} | {r['prior']} | {r['repo']} | "
                 f"{r['lens'] or ''} | {r['gaps'] or ''} |")

    L.append("\n## Cards with nothing written down\n")
    for area in model["areas"]:
        gone = [r for r in rows if r["area"] == area["title"] and r["grade"] == "undocumented"]
        if gone:
            L.append(f"- **{area['title']}** — " +
                     ", ".join(f"{r['addr']} {r['card']}" for r in gone))

    orphan = [r for r in rows if r["grade"] == "undocumented" and r["lens"]]
    if orphan:
        L.append("\n## Research done but never incorporated\n")
        L.append("A dedicated research lens exists and no profile cites it:\n")
        for r in orphan:
            L.append(f"- **{r['addr']} {r['card']}** — {r['lens']} records in "
                     f"`kb/research/refmodel-{r['addr'].replace('.', '-')}-*.jsonl`, unattached")

    OUT.write_text("\n".join(L) + "\n")
    print(f"{tot['documented']} documented, {tot['unread']} unread, {tot['undocumented']} undocumented "
          f"of {len(rows)} cards -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
