#!/usr/bin/env python3
"""Render docs/guides/<element>.md, one integration guide per stack element, from data only (TARGET T10.7, STATUS row 60).

Usage: python3 tools/render_guide.py            write every guide and print one line per element
       python3 tools/render_guide.py --check    exit 1 if a guide on disk differs from what the data derives

A guide is not prose written by hand. Every section is pulled from a record a reader can open:
  the element, standard, tool today and swap options   PASS.md B3 via docs/acceptance/matrix.json
  the operations a caller uses                          .claude/skills/cap-<element>/skill.json contract.operations
  what the adapters expose and cannot do                .claude/skills/cap-<element>-implement/skill.json adapters
  the runnable steps                                    harness/<name>/README.md step table, when a harness covers the element
  the definition of done and its status                 the implement skill's definition_of_done
An element with no harness gets a guide whose runnable section says so and names the gap; the acceptance
check counts a guide only when its runnable section carries a command that exists on disk.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / ".claude" / "skills"
GUIDES = ROOT / "docs" / "guides"
MATRIX = ROOT / "docs" / "acceptance" / "matrix.json"


def skill(name: str) -> dict | None:
    p = SKILLS / name / "skill.json"
    return json.loads(p.read_text()) if p.is_file() else None


def harness_steps(hdir: str | None) -> list[tuple[str, str]]:
    if not hdir:
        return []
    readme = ROOT / hdir / "README.md"
    steps = []
    for line in readme.read_text().splitlines() if readme.is_file() else []:
        m = re.match(r"^\|\s*(\d+\.\s[^|]+?)\s*\|\s*`([^`]+)`\s*\|", line)
        if m:
            steps.append((m.group(1), m.group(2)))
    if not steps and (ROOT / hdir / "test.sh").is_file():
        steps.append(("1. Run the gate", f"bash {hdir}/test.sh"))
    return steps


def first_sentence(s: str) -> str:
    s = (s or "").strip()
    return s.split(". ")[0].rstrip(".") if s else "-"


def render(el: dict) -> str:
    key = el["key"]
    ideal = skill(f"cap-{key}")
    impl = skill(f"cap-{key}-implement") or ideal   # since STATUS row 71 the implement facet is folded into the ideal
    steps = harness_steps(el.get("harness"))
    L = [f"# {el['element']}: integration guide", "",
         f"Generated by `tools/render_guide.py` from the records named in each section. Do not edit by hand. Source row: {el['source']}.", "",
         "| | |", "|---|---|",
         f"| Standard | {el['standard']} |",
         f"| Version on file | {el['sticks']['standard']['value']} |",
         f"| Tool today | {el['today']} |",
         f"| Swap options | {el['swap_options']} |",
         f"| Skills | {', '.join('`' + s + '`' for s in el['skills']) or 'none'} |",
         f"| Harness | {'`' + el['harness'] + '`' if el.get('harness') else 'none'} |", ""]

    L += ["## What a caller uses", ""]
    ops = ((ideal or {}).get("contract") or {}).get("operations") or []
    if ops:
        L += ["| Operation | Input | Output | Origin |", "|---|---|---|---|"]
        for op in ops:
            L.append(f"| {first_sentence(op.get('name'))} | {first_sentence(op.get('input'))} | {first_sentence(op.get('output'))} | {op.get('origin', '-')} |")
        L.append(f"\nFrom `cap-{key}` contract.operations; a row marked proposed is this repo's design, not a sourced fact.")
    else:
        L.append(f"Gap: `cap-{key}` declares no operations.")
    L.append("")

    L += ["## Adapters", ""]
    ads = (impl or {}).get("adapters") or []
    if ads:
        L += ["| Role | Entity | Exposes | Cannot |", "|---|---|---|---|"]
        for a in ads:
            L.append(f"| {a.get('role', '-')} | {a.get('entity', '-')} | {first_sentence(a.get('maps_to'))} | {first_sentence(a.get('cannot'))} |")
        L.append(f"\nFrom `cap-{key}-implement` adapters. Product names live only here and in the harness adapter files.")
    else:
        L.append(f"Gap: `cap-{key}-implement` declares no adapters.")
    L.append("")

    L += ["## Runnable", ""]
    if steps:
        L += ["runnable: yes", "", "| Step | Command |", "|---|---|"]
        L += [f"| {s} | `{c}` |" for s, c in steps]
        L.append(f"\nFrom `{el['harness']}/README.md`. Every command runs here in dry-run mode; live mode needs the env vars in that README.")
    else:
        L += ["runnable: no", "", f"Gap: no harness covers {el['element']} yet. The measured run for this element waits on one (TARGET T9.6, T10.7)."]
    L.append("")

    dod = (impl or {}).get("definition_of_done") or {}
    L += ["## Definition of done", "",
          f"Status: {dod.get('status', 'none')}", "",
          f"Criterion: {first_sentence(dod.get('criterion'))}.", "",
          f"From `cap-{key}-implement` definition_of_done; only `tools/measure.py` may set the status to measured.", ""]
    return "\n".join(L) + "\n"


def main(argv: list[str]) -> int:
    m = json.loads(MATRIX.read_text())
    check = "--check" in argv
    stale, runnable = [], 0
    GUIDES.mkdir(parents=True, exist_ok=True)
    for el in m["elements"]:
        text = render(el)
        p = GUIDES / f"{el['key']}.md"
        if "runnable: yes" in text:
            runnable += 1
        if check:
            if not p.is_file() or p.read_text() != text:
                stale.append(str(p.relative_to(ROOT)))
        else:
            p.write_text(text)
            print(f"{el['key']}: {'runnable' if 'runnable: yes' in text else 'no runnable example'}")
    if check and stale:
        print("FAIL: stale guides: " + ", ".join(stale))
        return 1
    print(f"{len(m['elements'])} guides, {runnable} runnable")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
