#!/usr/bin/env python3
"""Generate docs/skill-graph.md from the Composes with sections of every skill.

Usage: python3 tools/skill_graph.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_skills import SKILLS, ROOT, ROOT_SKILL, LAYERS, frontmatter, composes_with  # noqa: E402

LAYER_TITLES = {
    "core-": "Core", "cap-": "Capabilities", "xc-": "Cross-cutting", "seam-": "Seams",
    "compose-": "Composition", "build-": "Build disciplines",
}


def main() -> int:
    skills = {}
    for d in sorted(SKILLS.iterdir()):
        md = d / "SKILL.md"
        if not md.is_file():
            continue
        fm, body = frontmatter(md.read_text())
        cw = composes_with(body) or (set(), set())
        skills[d.name] = (fm.get("description", "") if fm else "", cw[0], cw[1])

    out = ["# Skill graph", "", "Generated by `tools/skill_graph.py` from each skill's Composes with section. Do not edit by hand.", ""]
    out += ["```mermaid", "graph TD"]
    for name, (_, builds_on, _) in skills.items():
        for b in sorted(builds_on):
            out.append(f"    {b} --> {name}")
    out += ["```", ""]
    for prefix in ("", *LAYERS):
        members = [n for n in skills if (n == ROOT_SKILL if prefix == "" else n.startswith(prefix))]
        if not members:
            continue
        out.append(f"## {LAYER_TITLES.get(prefix, 'Root')}")
        out.append("")
        out.append("| Skill | Builds on | Used by | Purpose |")
        out.append("|---|---|---|---|")
        for n in members:
            desc, bo, ub = skills[n]
            short = desc.split(". ")[0].rstrip(".")
            out.append(f"| `{n}` | {', '.join(f'`{x}`' for x in sorted(bo)) or '-'} | {', '.join(f'`{x}`' for x in sorted(ub)) or '-'} | {short} |")
        out.append("")
    (ROOT / "docs" / "skill-graph.md").write_text("\n".join(out))
    print(f"wrote docs/skill-graph.md with {len(skills)} skills")
    return 0


if __name__ == "__main__":
    sys.exit(main())
