#!/usr/bin/env python3
"""Generate docs/skill-graph.md from every skill.json.

Usage: python3 tools/skill_graph.py
Reads the data (name, layer, description, composes_with) rather than the rendered SKILL.md,
so the graph cannot drift from the source the validator checks.
A builds_on target with no skill.json on disk is reported as a warning and counted, rather than
having its edge dropped from the mermaid graph in silence.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_skills import SKILLS, ROOT, ROOT_SKILL, LAYERS  # noqa: E402

LAYER_TITLES = {
    "root": "Root", "core": "Core", "cap": "Capabilities", "xc": "Cross-cutting",
    "seam": "Seams", "compose": "Composition", "build": "Build disciplines",
}


def main() -> int:
    skills = {}
    for d in sorted(SKILLS.iterdir()):
        sj = d / "skill.json"
        if not sj.is_file():
            continue
        sk = json.loads(sj.read_text())
        cw = sk.get("composes_with") or {}
        skills[sk.get("name", d.name)] = (
            sk.get("layer", ""),
            sk.get("description", ""),
            set(cw.get("builds_on") or []),
            set(cw.get("used_by") or []),
        )

    dangling = 0
    out = ["# Skill graph", "", "Generated by `tools/skill_graph.py` from every skill.json. Do not edit by hand.", ""]
    out += ["```mermaid", "graph TD"]
    for name, (_, _, builds_on, _) in skills.items():
        for b in sorted(builds_on):
            if b in skills:
                out.append(f"    {b} --> {name}")
            else:
                # Never drop an edge in silence: a builds_on target with no skill.json on disk
                # (a manifest skill not yet written) would otherwise leave the graph quietly incomplete.
                print(f"warning: {name} builds_on {b}, which was not loaded; edge omitted from the graph")
                dangling += 1
    out += ["```", ""]
    for layer in LAYERS:
        members = [n for n in skills if (n == ROOT_SKILL if layer == "root" else skills[n][0] == layer)]
        if not members:
            continue
        out += [f"## {LAYER_TITLES.get(layer, layer)}", "", "| Skill | Builds on | Used by | Purpose |", "|---|---|---|---|"]
        for n in sorted(members):
            _, desc, bo, ub = skills[n]
            short = desc.split(". ")[0].rstrip(".")
            bo_w = ", ".join(f"`{x}`" for x in sorted(bo)) or "-"
            ub_w = ", ".join(f"`{x}`" for x in sorted(x for x in ub if x in skills)) or "-"
            out.append(f"| `{n}` | {bo_w} | {ub_w} | {short} |")
        out.append("")
    (ROOT / "docs" / "skill-graph.md").write_text("\n".join(out) + "\n")
    print(f"wrote docs/skill-graph.md with {len(skills)} skills, {dangling} dangling builds_on edges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
